// GENERATED by custom/tools/trim_settings_pages.py from upstream SettingsPagesModel.qml - do not edit
import QtQml.Models
import QtQml

import QGroundControl
import QGroundControl.Controls

ListModel {
    property QtObject _page0SectionState: QtObject {
        property var _appSettings: QGroundControl.settingsManager.appSettings
        property var _sectionVisibility: [
            (QGroundControl.settingsManager.appSettings.qLocaleLanguage.userVisible || QGroundControl.settingsManager.appSettings.indoorPalette.userVisible || QGroundControl.settingsManager.appSettings.followTarget.userVisible || QGroundControl.settingsManager.appSettings.audioVolume.userVisible || QGroundControl.settingsManager.appSettings.androidDontSaveToSDCard.userVisible || QGroundControl.settingsManager.appSettings.uiScalePercent.userVisible || QGroundControl.settingsManager.appSettings.savePath.userVisible || QGroundControl.settingsManager.appSettings.clearSettingsNextBoot.userVisible),
            (QGroundControl.settingsManager.appSettings.preferredFirmwareClass.userVisible || QGroundControl.settingsManager.appSettings.preferredVehicleClass.userVisible),
            (QGroundControl.settingsManager.unitsSettings.userVisible) && (QGroundControl.settingsManager.unitsSettings.horizontalDistanceUnits.userVisible || QGroundControl.settingsManager.unitsSettings.verticalDistanceUnits.userVisible || QGroundControl.settingsManager.unitsSettings.areaUnits.userVisible || QGroundControl.settingsManager.unitsSettings.speedUnits.userVisible || QGroundControl.settingsManager.unitsSettings.temperatureUnits.userVisible)
        ]
    }

    property QtObject _page1SectionState: QtObject {
        property var hasChecklist: QGroundControl.corePlugin.options.preFlightChecklistUrl.toString().length
        property var useChecklistValue: QGroundControl.settingsManager.appSettings.useChecklist.value
        property var virtualJoystickOn: QGroundControl.settingsManager.appSettings.virtualJoystick.rawValue
        property var _sectionVisibility: [
            (QGroundControl.settingsManager.appSettings.useChecklist.userVisible || QGroundControl.settingsManager.appSettings.enforceChecklist.userVisible || QGroundControl.settingsManager.appSettings.enableMultiVehiclePanel.userVisible || QGroundControl.settingsManager.flyViewSettings.keepMapCenteredOnVehicle.userVisible || QGroundControl.settingsManager.flyViewSettings.showLogReplayStatusBar.userVisible || QGroundControl.settingsManager.flyViewSettings.showSimpleCameraControl.userVisible || QGroundControl.settingsManager.flyViewSettings.updateHomePosition.userVisible || QGroundControl.settingsManager.flyViewSettings.enableAutomaticMissionPopups.userVisible),
            (QGroundControl.settingsManager.flyViewSettings.guidedMinimumAltitude.userVisible || QGroundControl.settingsManager.flyViewSettings.guidedMaximumAltitude.userVisible || QGroundControl.settingsManager.flyViewSettings.maxGoToLocationDistance.userVisible || QGroundControl.settingsManager.flyViewSettings.forwardFlightGoToLocationLoiterRad.userVisible || QGroundControl.settingsManager.flyViewSettings.goToLocationRequiresConfirmInGuided.userVisible),
            true,
            (QGroundControl.settingsManager.appSettings.virtualJoystick.userVisible || QGroundControl.settingsManager.appSettings.virtualJoystickAutoCenterThrottle.userVisible || QGroundControl.settingsManager.appSettings.virtualJoystickLeftHandedMode.userVisible),
            (QGroundControl.settingsManager.flyViewSettings.showAdditionalIndicatorsCompass.userVisible || QGroundControl.settingsManager.flyViewSettings.lockNoseUpCompass.userVisible || QGroundControl.settingsManager.flyViewSettings.instrumentQmlFile2.userVisible)
        ]
    }

    property QtObject _page7SectionState: QtObject {
        property var settingsManager: QGroundControl.settingsManager
        property var logSettings: settingsManager.logManagerSettings
        property var diskLoggingEnabledValue: logSettings.diskLoggingEnabled.rawValue
        property var logSavePath: settingsManager.appSettings.logSavePath
        property var _sectionVisibility: [
            (QGroundControl.settingsManager.logManagerSettings.diskLoggingEnabled.userVisible || QGroundControl.settingsManager.logManagerSettings.diskLoggingMaxFileSizeMB.userVisible || QGroundControl.settingsManager.logManagerSettings.diskLoggingMaxBackupFiles.userVisible || QGroundControl.settingsManager.logManagerSettings.saveFormat.userVisible),
            (QGroundControl.settingsManager.appSettings.showAppLogTimestampAsElapsedTime.userVisible || QGroundControl.settingsManager.appSettings.gstDebugLevel.userVisible)
        ]
    }

    property QtObject _page12SectionState: QtObject {
        property var ridSettings: QGroundControl.settingsManager.remoteIDSettings
        property bool isEURegion: ridSettings.region.rawValue === RemoteIDSettings.RegionOperation.EU
        property bool isFAARegion: ridSettings.region.rawValue === RemoteIDSettings.RegionOperation.FAA
        property var sendBasicIDOn: ridSettings.sendBasicID.rawValue
        property var sendSelfIDOn: ridSettings.sendSelfID.rawValue
        property bool locationIsFixed: ridSettings.locationType.rawValue === RemoteIDSettings.LocationType.FIXED
        property bool classificationIsEU: ridSettings.classificationType.rawValue === RemoteIDSettings.ClassificationType.EU
        property var _sectionVisibility: [
            (QGroundControl.settingsManager.remoteIDSettings.region.userVisible),
            (QGroundControl.settingsManager.remoteIDSettings.sendBasicID.userVisible || QGroundControl.settingsManager.remoteIDSettings.basicIDType.userVisible || QGroundControl.settingsManager.remoteIDSettings.basicIDUaType.userVisible || QGroundControl.settingsManager.remoteIDSettings.basicID.userVisible),
            (QGroundControl.settingsManager.remoteIDSettings.sendOperatorID.userVisible || QGroundControl.settingsManager.remoteIDSettings.operatorIDType.userVisible || QGroundControl.settingsManager.remoteIDSettings.operatorIDEU.userVisible || QGroundControl.settingsManager.remoteIDSettings.operatorIDFAA.userVisible),
            (QGroundControl.settingsManager.remoteIDSettings.sendSelfID.userVisible || QGroundControl.settingsManager.remoteIDSettings.selfIDType.userVisible || QGroundControl.settingsManager.remoteIDSettings.selfIDFree.userVisible || QGroundControl.settingsManager.remoteIDSettings.selfIDExtended.userVisible || QGroundControl.settingsManager.remoteIDSettings.selfIDEmergency.userVisible),
            (QGroundControl.settingsManager.remoteIDSettings.locationType.userVisible || QGroundControl.settingsManager.remoteIDSettings.latitudeFixed.userVisible || QGroundControl.settingsManager.remoteIDSettings.longitudeFixed.userVisible || QGroundControl.settingsManager.remoteIDSettings.altitudeFixed.userVisible),
            true,
            true,
            (isEURegion) && (QGroundControl.settingsManager.remoteIDSettings.classificationType.userVisible || QGroundControl.settingsManager.remoteIDSettings.categoryEU.userVisible || QGroundControl.settingsManager.remoteIDSettings.classEU.userVisible)
        ]
    }

    property QtObject _page14SectionState: QtObject {
        property var videoSource: QGroundControl.settingsManager.videoSettings.videoSource.rawValue
        property var autoStreamConfig: QGroundControl.videoManager.autoStreamConfigured
        property bool sourceDisabled: videoSource === QGroundControl.settingsManager.videoSettings.disabledVideoSource
        property var isStreamSource: QGroundControl.videoManager.isStreamSource
        property var rtpLatencyVisible: !QGroundControl.settingsManager.videoSettings.lowLatencyMode.rawValue
        property var _sectionVisibility: [
            (QGroundControl.settingsManager.videoSettings.videoSource.userVisible),
            (!sourceDisabled && !autoStreamConfig) && (QGroundControl.settingsManager.videoSettings.rtspUrl.userVisible || QGroundControl.settingsManager.videoSettings.tcpUrl.userVisible || QGroundControl.settingsManager.videoSettings.udpUrl.userVisible),
            (!sourceDisabled) && (QGroundControl.settingsManager.videoSettings.aspectRatio.userVisible || QGroundControl.settingsManager.videoSettings.disableWhenDisarmed.userVisible || QGroundControl.settingsManager.videoSettings.lowLatencyMode.userVisible || QGroundControl.settingsManager.videoSettings.rtpJitterLatencyMs.userVisible || QGroundControl.settingsManager.videoSettings.rtspAutoReconnect.userVisible || QGroundControl.settingsManager.videoSettings.forceCpuVideoPath.userVisible || QGroundControl.settingsManager.videoSettings.forceVideoDecoder.userVisible),
            (!sourceDisabled) && (QGroundControl.settingsManager.videoSettings.recordingFormat.userVisible || QGroundControl.settingsManager.videoSettings.enableStorageLimit.userVisible || QGroundControl.settingsManager.videoSettings.maxVideoSize.userVisible)
        ]
    }


    ListElement {
        name: qsTranslate("SettingsPages.json", "General")
        nameKey: "General"
        url: "qrc:/qml/QGroundControl/AppSettings/GeneralSettings.qml"
        iconUrl: "qrc:/res/QGCLogoWhite.svg"
        sections: function() { return [] }
        pageVisible: function() { return true }
    }






    ListElement {
        name: qsTranslate("SettingsPages.json", "Comm Links")
        nameKey: "Comm Links"
        url: "qrc:/qml/QGroundControl/AppSettings/CommLinksSettings.qml"
        iconUrl: "qrc:/InstrumentValueIcons/usb.svg"
        sections: function() { return [] }
        pageVisible: function() { return true }
    }



    ListElement {
        name: qsTranslate("SettingsPages.json", "Maps")
        nameKey: "Maps"
        url: "qrc:/qml/QGroundControl/AppSettings/MapsSettings.qml"
        iconUrl: "qrc:/InstrumentValueIcons/globe.svg"
        sections: function() {
            return [
                {
                    index: 0,
                    name: qsTranslate("Maps.SettingsUI.json", "Map Provider"),
                    searchTerms: ["maps map provider satellite terrain street hybrid google bing", qsTranslate("Maps.SettingsUI.json", "Map Provider").toLowerCase(), qsTranslate("Maps.SettingsUI.json", "map provider").toLowerCase(), qsTranslate("Maps.SettingsUI.json", "satellite").toLowerCase(), qsTranslate("Maps.SettingsUI.json", "terrain").toLowerCase(), qsTranslate("Maps.SettingsUI.json", "street").toLowerCase(), qsTranslate("Maps.SettingsUI.json", "hybrid").toLowerCase(), qsTranslate("Maps.SettingsUI.json", "google").toLowerCase(), qsTranslate("Maps.SettingsUI.json", "bing").toLowerCase()],
                    visible: true
                },
                {
                    index: 1,
                    name: qsTranslate("Maps.SettingsUI.json", "Offline Maps"),
                    searchTerms: ["maps offline maps offline download cache tile set", qsTranslate("Maps.SettingsUI.json", "Offline Maps").toLowerCase(), qsTranslate("Maps.SettingsUI.json", "offline").toLowerCase(), qsTranslate("Maps.SettingsUI.json", "download").toLowerCase(), qsTranslate("Maps.SettingsUI.json", "cache").toLowerCase(), qsTranslate("Maps.SettingsUI.json", "tile set").toLowerCase()],
                    visible: true
                },
                {
                    index: 2,
                    name: qsTranslate("Maps.SettingsUI.json", "Tokens"),
                    searchTerms: ["maps tokens token api key tianditu mapbox esri vworld openaip", qsTranslate("Maps.SettingsUI.json", "Tokens").toLowerCase(), qsTranslate("Maps.SettingsUI.json", "token").toLowerCase(), qsTranslate("Maps.SettingsUI.json", "api key").toLowerCase(), qsTranslate("Maps.SettingsUI.json", "tianditu").toLowerCase(), qsTranslate("Maps.SettingsUI.json", "mapbox").toLowerCase(), qsTranslate("Maps.SettingsUI.json", "esri").toLowerCase(), qsTranslate("Maps.SettingsUI.json", "vworld").toLowerCase(), qsTranslate("Maps.SettingsUI.json", "openaip").toLowerCase()],
                    visible: (QGroundControl.settingsManager.appSettings.tiandituToken.userVisible || QGroundControl.settingsManager.appSettings.mapboxToken.userVisible || QGroundControl.settingsManager.appSettings.esriToken.userVisible || QGroundControl.settingsManager.appSettings.vworldToken.userVisible || QGroundControl.settingsManager.appSettings.openaipToken.userVisible)
                },
                {
                    index: 3,
                    name: qsTranslate("Maps.SettingsUI.json", "Mapbox Login"),
                    searchTerms: ["maps mapbox login mapbox account style", qsTranslate("Maps.SettingsUI.json", "Mapbox Login").toLowerCase(), qsTranslate("Maps.SettingsUI.json", "mapbox").toLowerCase(), qsTranslate("Maps.SettingsUI.json", "account").toLowerCase(), qsTranslate("Maps.SettingsUI.json", "style").toLowerCase()],
                    visible: (QGroundControl.settingsManager.appSettings.mapboxAccount.userVisible || QGroundControl.settingsManager.appSettings.mapboxStyle.userVisible)
                },
                {
                    index: 4,
                    name: qsTranslate("Maps.SettingsUI.json", "Custom Map URL"),
                    searchTerms: ["maps custom map url custom map wms tile url tile server", qsTranslate("Maps.SettingsUI.json", "Custom Map URL").toLowerCase(), qsTranslate("Maps.SettingsUI.json", "custom map").toLowerCase(), qsTranslate("Maps.SettingsUI.json", "wms").toLowerCase(), qsTranslate("Maps.SettingsUI.json", "tile url").toLowerCase(), qsTranslate("Maps.SettingsUI.json", "tile server").toLowerCase()],
                    visible: (QGroundControl.settingsManager.appSettings.customURL.userVisible)
                },
                {
                    index: 5,
                    name: qsTranslate("Maps.SettingsUI.json", "Tile Cache"),
                    searchTerms: ["maps tile cache cache disk size memory size", qsTranslate("Maps.SettingsUI.json", "Tile Cache").toLowerCase(), qsTranslate("Maps.SettingsUI.json", "cache").toLowerCase(), qsTranslate("Maps.SettingsUI.json", "disk size").toLowerCase(), qsTranslate("Maps.SettingsUI.json", "memory size").toLowerCase(), qsTranslate("Maps.SettingsUI.json", "tile cache").toLowerCase()],
                    visible: (QGroundControl.settingsManager.mapsSettings.maxCacheDiskSize.userVisible || QGroundControl.settingsManager.mapsSettings.maxCacheMemorySize.userVisible)
                }
            ]
        }
        pageVisible: function() { return true }
    }

    ListElement {
        name: qsTranslate("SettingsPages.json", "NTRIP/RTK")
        nameKey: "NTRIP/RTK"
        url: "qrc:/qml/QGroundControl/AppSettings/NTRIPSettings.qml"
        iconUrl: "qrc:/InstrumentValueIcons/globe.svg"
        sections: function() { return [] }
        pageVisible: function() { return QGroundControl.settingsManager && QGroundControl.settingsManager.ntripSettings !== undefined }
    }











    ListElement {
        name: qsTranslate("HHUSettingsPages", "Advanced")
        nameKey: "HHU Advanced"
        url: "qrc:/qml/QGroundControl/AppSettings/HHUAdvancedSettings.qml"
        iconUrl: "qrc:/InstrumentValueIcons/cog.svg"
        sections: function() { return [] }
        pageVisible: function() { return true }
    }

    ListElement {
        name: qsTranslate("HHUSettingsPages", "About")
        nameKey: "HHU About"
        url: "qrc:/qml/QGroundControl/AppSettings/HHUAboutSettings.qml"
        iconUrl: "qrc:/InstrumentValueIcons/information-outline.svg"
        sections: function() { return [] }
        pageVisible: function() { return true }
    }
}
