"""Build src/qml/SettingsPagesModel.qml from the upstream generated model.

Upstream generates SettingsPagesModel.qml at build time from
src/AppSettings/pages/SettingsPages.json. The customer build keeps only the
pages listed in KEEP (需求说明 V1.0 §3.4: 通用 / 连接 / 地图 / 差分 / 高级 / 关于);
this script copies the generated file, drops every other ListElement, removes
the sub-sections of pages replaced by HHU pages and appends the HHU pages.
Re-run after upgrading QGC:

    python custom/tools/trim_settings_pages.py <build>/qml/QGroundControl/AppSettings/SettingsPagesModel.qml
"""
import pathlib
import re
import sys

KEEP = {"General", "Comm Links", "Maps", "NTRIP/RTK"}
# Upstream pages replaced by hand-written HHU pages (custom.qrc): their section list does not apply
NO_SECTIONS = {"General", "Comm Links", "NTRIP/RTK"}

HHU_PAGES = """
    ListElement {
        name: qsTranslate("HHUSettingsPages", "Advanced")
        nameKey: "HHU Advanced"
        url: "qrc:/qml/QGroundControl/AppSettings/HHUAdvancedSettings.qml"
        iconUrl: "qrc:/InstrumentValueIcons/cog.svg"
        sections: function() { return [] }
        pageVisible: function() { return true }
    }

    ListElement {
        name: qsTranslate("HHUSettingsPages", "About")
        nameKey: "HHU About"
        url: "qrc:/qml/QGroundControl/AppSettings/HHUAboutSettings.qml"
        iconUrl: "qrc:/InstrumentValueIcons/information-outline.svg"
        sections: function() { return [] }
        pageVisible: function() { return true }
    }
"""

src = pathlib.Path(sys.argv[1]).read_text(encoding="utf-8")
out_path = pathlib.Path(__file__).resolve().parent.parent / "src" / "qml" / "SettingsPagesModel.qml"


def split_elements(text):
    """Yield (start, end, nameKey) for each top-level ListElement block."""
    for m in re.finditer(r"\n    ListElement \{", text):
        depth, i = 0, m.start() + 1
        while True:
            c = text[i]
            if c == "{":
                depth += 1
            elif c == "}":
                depth -= 1
                if depth == 0:
                    break
            i += 1
        block = text[m.start():i + 1]
        key = re.search(r'nameKey: "([^"]*)"', block)
        yield m.start(), i + 1, key.group(1) if key else None


def drop_sections(block):
    """Replace the `sections: function() { ... }` body by an empty list."""
    start = block.index("        sections: function() {")
    depth, i = 0, block.index("{", start)
    while True:
        if block[i] == "{":
            depth += 1
        elif block[i] == "}":
            depth -= 1
            if depth == 0:
                break
        i += 1
    return block[:start] + "        sections: function() { return [] }" + block[i + 1:]


pieces, last, kept = [], 0, []
for start, end, key in split_elements(src):
    pieces.append(src[last:start])
    if key in KEEP:
        block = src[start:end]
        pieces.append(drop_sections(block) if key in NO_SECTIONS else block)
        kept.append(key)
    last = end
tail = src[last:]
closing = tail.rindex("}")
pieces.append(tail[:closing] + HHU_PAGES + tail[closing:])

header = "// GENERATED by custom/tools/trim_settings_pages.py from upstream SettingsPagesModel.qml - do not edit\n"
out_path.write_text(header + "".join(pieces), encoding="utf-8")
print("kept:", kept, "+ HHU Advanced, HHU About")
